services:
  - type: web
    name: criminalproject
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: ""
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: criminal_detection_system.settings
      - key: SECRET_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: PORT
        value: 8000