services:
  - type: web
    name: criminal-detection-system
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: ""
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: criminal_detection_system.settings
      - key: SECRET_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 4

  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction