services:
  - type: web
    name: criminal-detection-system
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT criminal_detection_system.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.15
      - key: DJANGO_SETTINGS_MODULE
        value: criminal_detection_system.settings
      - key: SECRET_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: PORT
        value: 8000

  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction